---
kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: ubuntu:19.04
  commands:
  - apt-get update
  - apt-get install -y git llvm clang lld cmake make ninja-build curl python3 rsync ccache
  - ./configure.sh
  - ninja

- name: Docker Release
  image: plugins/docker
  settings:
    repo: esplinux/bootstrap
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event: tag

- name: GitHub Release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: ghr_token
    files: '*.tgz'
    overwrite: true
  when:
    event: tag
