---
kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: ubuntu:19.04
  commands:
  - apt-get update
  - apt-get install -y git llvm clang lld cmake make ninja-build curl python3 rsync ccache
  - ./configure.sh
  - ninja

- name: Publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: ghr_token
    files: '*.tgz'
    overwrite: true
  when:
    event: tag
