---
kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: fedora:31
  commands:
  - sudo dnf clean all
  - sudo dnf -y install --refresh git llvm clang lld cmake make ninja-build findutils rsync glibc-static python2.7 python which ccache diffutils findutils
  - ./configure.sh
  - ninja

- name: Publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: ghr_token
    files: '*.tgz'
