# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: Bootstrap
  timeoutInMinutes: 0
  container:
    image: quay.io/buildah/stable
    options: --privileged --cap-add SYS_ADMIN --device /dev/fuse

  # Test Buildah
  steps:
  - script: |
      buildah pull busybox
      buildah login -u $(docker-user) -p $(docker-pass) docker.io
      buildah logout docker.io
    displayName: 'Test Buildah'

  # Install build tools
  steps:
  - script: |
      sudo dnf -y install buildah git llvm clang lld cmake make ninja-build findutils rsync glibc-static python2.7 python which
    displayName: 'Install Prerequisites'

  - script: ./configure.sh
    displayName: 'Configure'

  - script: TERM=dumb ninja musl
    displayName: 'Build MUSL'

  - script: TERM=dumb ninja clang
    displayName: 'Build Clang'

  - script: TERM=dumb ninja toybox dash curl
    displayName: 'Build Base [Toybox, Dash, Curl]'

  - script: |
      CONTAINER_NAME="esplinux/bootstrap" scripts/buildcontainer.sh musl clang toybox dash curl
      sudo buildah login -u $(docker-user) -p $(docker-pass) docker.io
      sudo buildah push esplinux/bootstrap docker://docker.io/esplinux/bootstrap
      sudo buildah logout docker.io
    displayName: 'Podman Bootstrap'

  - script: TERM=dumb ninja bash node
    displayName: 'Build Azure Deps [Bash Node]'

  - script: |
      CMD=node CONTAINER_NAME="esplinux/bootstrap-azurepipeline" scripts/buildcontainer.sh musl toybox dash clang bash node
      sudo buildah login -u $(docker-user) -p $(docker-pass) docker.io
      sudo buildah push esplinux/bootstrap-azurepipeline docker://docker.io/esplinux/bootstrap-azurepipeline
      sudo buildah logout docker.io
    displayName: 'Podman Bootstrap Azure Pipeline'

  # GitHub Release
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github.com_emolitor'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: 'Bootstrap' # Required when action == Edit || Action == Delete || TagSource == Manual
      assets: '*.tgz' #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
      assetUploadMode: 'delete' # Optional. Options: delete, replace
      isPreRelease: true # Optional
    displayName: 'Github Release'
