# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: Bootstrap
  timeoutInMinutes: 0
  container: 
    image: quay.io/buildah/stable
    options: --privileged --cap-add SYS_ADMIN --device /dev/fuse

  # Install build tools and buildah
  steps:
  - script: |
      sudo dnf -y install git clang lld cmake make ninja-build rsync findutils diffutils
    displayName: 'Install Prerequisites'

  - script: TERM=dumb ninja musl toybox dash bash
    displayName: 'Build Base [Musl, Toybox, Dash, Bash]'

  - script: |
      CONTAINER_NAME="esplinux/bootstrap-base" scripts/buildcontainer.sh musl toybox dash
      sudo buildah login -u $(docker-user) -p $(docker-pass) docker.io
      sudo buildah push esplinux/bootstrap-base docker://docker.io/esplinux/bootstrap-base
      sudo buildah logout docker.io
    displayName: 'Podman Bootstrap Base'

  - script: TERM=dumb ninja libcxx
    displayName: 'Build LibCXX'

  - script: TERM=dumb ninja lld
    displayName: 'Build LLD'

  - script: TERM=dumb ninja clang
    displayName: 'Build Clang'

  - script: |
      CONTAINER_NAME="esplinux/bootstrap" scripts/buildcontainer.sh musl toybox dash libcxx lld clang
      sudo podman login -u $(docker-user) -p $(docker-pass) docker.io
      sudo podman push esplinux/bootstrap docker://docker.io/esplinux/bootstrap
      sduo podman logout docker.io
    displayName: 'Podman Bootstrap'

  - script: TERM=dumb ninja nodejs
    displayName: 'Build NodeJS'

  - script: |
      CMD=node CONTAINER_NAME="esplinux/bootstrap-azurepipeline" scripts/buildcontainer.sh musl toybox dash libcxx lld clang bash nodejs
      sudo podman login -u $(docker-user) -p $(docker-pass) docker.io
      sudo podman push esplinux/bootstrap-azurepipeline docker://docker.io/esplinux/bootstrap-azurepipeline
      sudo podman logout docker.io
    displayName: 'Podman Bootstrap Azure Pipeline'

  # GitHub Release
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github.com_emolitor'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: 'Bootstrap' # Required when action == Edit || Action == Delete || TagSource == Manual
      assets: '*.tgz' #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
      assetUploadMode: 'delete' # Optional. Options: delete, replace
      isPreRelease: true # Optional
    displayName: 'Github Release'
