# Build bootrsap container used for scratch builds of ESPLinux

trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-18.04'

# Hack but XDG_RUNTIME_DIR is not set which will call rootless buildah to fail
variables:
  XDG_RUNTIME_DIR: /tmp
  AZURE_CACHE_REVISION: 0

jobs:
- job: Bootstrap
  timeoutInMinutes: 0
  container:
    image: quay.io/buildah/stable
    options: --privileged --cap-add SYS_ADMIN --device /dev/fuse

  steps:
  - script: |
      sudo dnf -y install buildah git llvm clang lld cmake make ninja-build findutils rsync glibc-static python2.7 python which
    displayName: 'Install Prerequisites'

  - script: ./configure.sh
    displayName: 'Configure'

  - script: TERM=dumb ninja fetch_sources
    displayName: 'Fetch Sources'

  - script: TERM=dumb ninja musl
    displayName: 'Build MUSL'

  - script: cd $(find -maxdepth 1 -type d -name 'llvm-*'); git rev-parse HEAD > ../llvmCache.key
    displayName: 'Generate llvmCache.key'

  - task: Cache@2
    inputs:
      key: 'clang | $(AZURE_CACHE_REVISION) | llvmCache.key'
      path: out-clang-llvm-10
    displayName: 'Cache Clang'

  - script: TERM=dumb ninja clang
    displayName: 'Build Clang'

  - script: TERM=dumb ninja toybox dash curl
    displayName: 'Build Base [Toybox, Dash, Curl]'

  - script: |
      CONTAINER_NAME="esplinux/bootstrap" scripts/buildcontainer.sh musl clang toybox dash curl
      buildah login -u $(docker-user) -p $(docker-pass) docker.io
      buildah push -f docker esplinux/bootstrap docker://docker.io/esplinux/bootstrap
      buildah logout docker.io
    displayName: 'Podman Bootstrap'

    - script: basename $(find -maxdepth 1 -type d -name 'node-*') > nodeCache.key
    displayName: 'Generate nodeCache.key'

    - task: Cache@2
    inputs:
      key: 'node | $(AZURE_CACHE_REVISION) | nodeCache.key'
      path: out-node-v12.15.0
    displayName: 'Cache Node'

  - script: TERM=dumb ninja bash node
    displayName: 'Build Azure Deps [Bash Node]'

  - script: |
      CMD=node CONTAINER_NAME="esplinux/bootstrap-azurepipeline" scripts/buildcontainer.sh musl toybox dash clang bash node
      buildah login -u $(docker-user) -p $(docker-pass) docker.io
      buildah push -f docker esplinux/bootstrap-azurepipeline docker://docker.io/esplinux/bootstrap-azurepipeline
      buildah logout docker.io
    displayName: 'Podman Bootstrap Azure Pipeline'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github.com_emolitor'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: 'Bootstrap' # Required when action == Edit || Action == Delete || TagSource == Manual
      assets: '*.tgz' #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
      assetUploadMode: 'delete' # Optional. Options: delete, replace
      isPreRelease: true # Optional
    displayName: 'Github Release'
