#!/bin/sh -e

LLVM_version=llvm-10
LINUX_version=linux-5.4.18
MUSL_version=musl-1.1.24
TOYBOX_version=toybox-HEAD
DASH_version=dash-0.5.10
BASH_version=bash-5.0
NODE_version=node-v12.15.0
BEARSSL_version=bearssl-HEAD
CURL_version=curl-7.68.0

check()
{
  if ! type "$1" > /dev/null; then
    echo "ERROR: $1 not found in path!"
    exit 1
  fi
}

check curl
check git
check find
check rsync
check cmp
check python2.7
check python3

check clang
check clang++
check llvm-ar
check llvm-ranlib
check lld

check make
check cmake
check ninja
check bash
check nproc

MARCH=broadwell
NPROC=$(nproc)
CC=$PWD/out-clang-$LLVM_version/bin/clang
CXX=$PWD/out-clang-$LLVM_version/bin/clang++
SYSROOT=$PWD/out-$MUSL_version
CFLAGS="-O3 -pipe -flto=thin -fexceptions -fasynchronous-unwind-tables -ffast-math -falign-functions=32 -march=$MARCH"
CXXFLAGS="-O3 -pipe -flto=thin -fexceptions -fasynchronous-unwind-tables -ffast-math -falign-functions=32 -march=$MARCH"
LDFLAGS="-flto=thin -Wl,--thinlto-cache-dir=/tmp"

if ! test -f "config.ninja"; then
  echo "Creating config.ninja"
  touch config.ninja
  echo "# Autogenerated Configuration" >> config.ninja
  echo "#============================" >> config.ninja
  echo "musl=$MUSL_version" >> config.ninja
  echo "linux=$LINUX_version" >> config.ninja
  echo "llvm=$LLVM_version" >> config.ninja
  echo "toybox=$TOYBOX_version" >> config.ninja
  echo "dash=$DASH_version" >> config.ninja
  echo "bash=$BASH_version" >> config.ninja
  echo "node=$NODE_version" >> config.ninja
  echo "bearssl=$BEARSSL_version" >> config.ninja
  echo "curl=$CURL_version" >> config.ninja
  echo "march=$MARCH" >> config.ninja
  echo "nproc=$NPROC" >> config.ninja
  echo "cc=$CC" >> config.ninja
  echo "cxx=$CXX" >> config.ninja
  echo "sysroot=$SYSROOT" >> config.ninja
  echo "cflags=$CFLAGS" >> config.ninja
  echo "cxxflags=$CXXFLAGS" >> config.ninja
  echo "ldflags=$LDFLAGS" >> config.ninja
fi
